### ISSUE TITLE
Create setup.py

### ISSUE THREAD

**Issue by sbliven** [citation-file-format/github2cff#4]
The current installation method (pip installation from github) fails due to the missing setup.py.

```
 pip install git+https://github.com/citation-file-format/github2cff
Collecting git+https://github.com/citation-file-format/github2cff
  Cloning https://github.com/citation-file-format/github2cff to /private/var/folders/qq/fxkml5kx4pq9jqxt09967pyc0000gn/T/pip-req-build-7igmln_b
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/local/miniconda3/envs/science3/lib/python3.7/tokenize.py", line 447, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/qq/fxkml5kx4pq9jqxt09967pyc0000gn/T/pip-req-build-7igmln_b/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/qq/fxkml5kx4pq9jqxt09967pyc0000gn/T/pip-req-build-7igmln_b/
```

Could you add a setup.py please?

**Comment by sdruskat** [comment]
Hi @sbliven, this project has been started at [Collaborations Workshop 2018](https://www.software.ac.uk/cw18) and we haven't had the time to keep working on it.

I personally think that it would be useful to have this as infrastructure once we have stabilized CFF to 1.1.0 (we're currently working towards it), but I don't have time to work on github2cff any time soon. 

The good news is: it's up for grabs, and we'd be really thankful if someone took to working on it :).
